apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
        - name: accountservice
          image: pierreas/accountservice-v1:1.0.0
          imagePullPolicy: Always 
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: "200m"        # Minimum CPU required for each pod
              memory: "128Mi"    # Minimum memory required for each pod
            limits:
              cpu: "500m"        # Maximum CPU allocated for each pod
              memory: "256Mi"    # Maximum memory allocated for each pod
      imagePullSecrets:
        - name: dockerhub-secret